name: agri_guide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  http: ^1.5.0
  image_picker: ^1.2.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_image.png
    - assets/images/logo.png
    - lib/assets/system_instruction.json
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/"
  

  
